Outer join support
vmware/differential-datalog pull request #1147
Opened 2022-01-28 01:56 UTC by mbudiu-vmw

@ryzhyk please check the rust changes, requested by clippy.

2022-01-28 01:57 UTC, mbudiu-vmw commented
@lalithsuresh the code is relatively convoluted, most useful would be to test it on some real data

2022-01-28 01:58 UTC, mbudiu-vmw commented
Fixes #1090

2022-02-10 19:01 UTC, lalithsuresh requested changes
We need a couple of tests with actual data in `JooqProviderTestBase`.

2022-02-25 01:51 UTC, mbudiu-vmw commented
@lalithsuresh this adds a runtime test for a left join.
Hopefully this completes the support for outer joins in the SQL to DDlog compiler.

2022-02-25 17:52 UTC, lalithsuresh approved these changes
LGTM. Just some nits.

2022-02-25 17:52 UTC, lalithsuresh commented on sql/src/main/java/com/vmware/ddlog/translator/JoinInfo.java
> +    protected final HashMap<String, String> leftToRightColumn;
Odd to not use the interface types in the declarations (Map, Set) instead of the implementation (HashMap, HashSet)

2022-02-25 17:52 UTC, lalithsuresh commented on sql/src/test/java/ddlog/JooqProviderTestBase.java
> +    public void testJoin() {
`testLeftJoin`

2022-02-26 02:04 UTC, merged