initial syntax highlighting for ddlog vscode
vmware/differential-datalog pull request #829
Opened 2020-11-27 05:24 UTC by desharchana19

Added source code for ddlog language extension and theme extension

2020-11-30 22:32 UTC, mbudiu-vmw requested changes
By testing I found a bunch of errors in the highlighting. Some of them are already in this review, but I will list more - if there are any - after a revision. This grammar is large and it's not easy to review; I would have preferred to have the changes be committed gradually and reviewed one by one, but we'll have to work with what we have now. There are some parts I haven't reviewed yet carefully.

2020-11-30 22:32 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/src/syntax/entity.json5
> +                    "name": "entity.name.function.ddlog",
why are all these named "entity.name.function.ddlog"?

2020-11-30 22:32 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/src/syntax/entity.json5
> +                    "match": "(?<=')([A-Z][a-zA-Z0-9_]*)",
I think that the apostrophe should be part of the type variable.

2020-11-30 22:32 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/src/syntax/entity.json5
> +                    "match": "(?<=(\\|))(\\s*)([A-Z][a-zA-Z0-9_]*)",
| exists both as a type constructor and as a binary expression. I hope this is used within the right context, but I had the impression that the matching of | as a constructor alternative does not work very well.

2020-11-30 22:32 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/src/syntax/entity.json5
> +                    "begin": "\\b(typedef)\\s*([a-zA-Z_][a-zA-Z0-9_]*)(=)([A-Z][a-zA-Z0-9_]+)",
after = you have a type_spec in the ddlog grammar, which is not just an identifier as in your description here. Also, 
there are no optional spaces in your regex.

2020-11-30 22:32 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/syntaxes/ddlog.tmLanguage.json
> +{
is this file generated by some tools? If so it should not be in the repository but in .gitignore.

2020-11-30 22:32 UTC, mbudiu-vmw commented on tools/vscode/ddlog-theme/.gitignore
> +ddlogtheme-0.0.1.vsix
This should be *.vsix

2020-11-30 22:32 UTC, mbudiu-vmw commented on tools/vscode/ddlog-theme/CHANGELOG.md
> +# Change Log
We do not really maintain change logs anymore, these are maintained by git automatically, so you can probably delete this file.

2020-12-03 03:56 UTC, desharchana19 commented on tools/vscode/ddlog-language/gulpfile.js
> +  done()
the file defines various gulp tasks like compile-json. The command gulp compile-json can be used to generate textmate grammer file

2020-12-03 04:23 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/constant.json5
> +                    "comment": "Floating point literal (with exponent)",
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:23 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/base.json5
> +  }
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:23 UTC, desharchana19 commented on tools/vscode/ddlog-language/language-configuration.json
> +
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:25 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/base.json5
> +  }
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:27 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/constant.json5
> +                    "comment": "Floating point literal (without exponent)",
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:28 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/keyword.json5
> +                    "match": "\\s(else|if|in|for|return|control|skip|continue|break)\\s"
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:29 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/keyword.json5
> +                    "match": "\\b(input|output|relation|function|match|rule)\\b"
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:30 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/punctuation.json5
> +
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:31 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/meta.json5
> +                        "3": {
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:32 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/meta.json5
> +                    "end": "[\\{\\=]",
Modified code
https://github.com/vmware/differential-datalog/pull/829/commits/0b469a5a8aaf77664435f92148000a500ab7e05f

2020-12-03 04:35 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/src/good/punctuation.json5
> +
There is no need to reply to every comment.

2020-12-03 04:42 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/string.json5
> +                    "name": "string.quoted.interpolated.ddlog",
Modified code

2020-12-03 09:11 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/type.json5
> +                    "match": "\\b([A-Za-z][_A-Za-z0-9]+)\\b(?=<[_a-zA-Z']+>)",
Type parameters are separated using begin"/"end pair. The pattern is "entity.name.type.param.ddlog".

This pattern is for type name

2020-12-03 09:28 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/variable.json5
> +                    "name": "variable.language.ddlog",
These are variations of variable - parameter variable, local variable

2020-12-03 10:22 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/meta.json5
> +                        "0": {
1 refers to "function" pattern in begin

2020-12-03 10:30 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/syntax/entity.json5
> +                    "match": "\\b(?<=function)(\\b)([a-z_][a-zA-Z0-9_]*)",
This pattern identifies function name

2020-12-03 10:33 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/syntax/entity.json5
> +                    "name": "entity.name.function.ddlog",
These patterns identify function name

2020-12-05 09:33 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/meta.json5
> +                            "include": "#entity"
entity.name.type-variable.ddlog is needed for declaration of arguments like 'A. 

function f(arg1: 'A, arg2: type2<'A,'B>): 'A {
    var x: 'A = arg1;
    x
}

2020-12-05 11:12 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/meta.json5
> +                            "include": "#entity"
modified code to fix this

2020-12-10 18:56 UTC, Kixiron commented
Any progress on this?

2020-12-10 18:58 UTC, mbudiu-vmw commented
As you can see, the progress is constant, but we're not done. Once this round of revisions completes I will do another review.

2020-12-10 18:59 UTC, mbudiu-vmw commented
You should be able to use this grammar for syntax highlighting, even if it has bugs, it still does something.

2020-12-11 06:49 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/keyword.json5
> +                    "match": "\\b(import|extern|as)\\b"
import statement can have as clause

2020-12-23 21:17 UTC, mbudiu-vmw requested changes

2020-12-23 21:17 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/src/good/type.json5
> +                    "match": "\\b(typedef)\\s*([a-zA-Z_][a-zA-Z0-9_]*)\\s*(=)\\s*(bigint|bit|bool|signed|double|float|string|Vec|Ref|Set|Map)(\\b)",
these rules for typedef are too specific. The grammar of typedef is 
```
"typedef" type_name (* unique type name *)
            ["<" typevar_name [("," typevar_name)*] ">"] 
            "=" type_spec (* type definition *)
```

I suspect you can parallel this definition in your grammar. Having all these base types is too specific, you should probably have a rule for type_spec.

2020-12-23 21:17 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/src/good/type.json5
> +        "type": {
you sould probably call this `typedef` and not `type`

2020-12-23 21:17 UTC, mbudiu-vmw commented on tools/vscode/ddlog-language/src/syntax/operator.json5
> +                    "match": ":\\s*(?=(\\(\\s*)\\s*(bigint|bit|bool|signed|double|float|string|Vec|Ref|Set|Map)(\\b))",
all these rules should use type_spec

2020-12-24 06:03 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/constant.json5
> +                    "comment": "Floating point literal (exponent)",
With this pattern scope of decimal e.g. 1 is  constant.numeric.float.ddlog instead of constant.numeric.integer.decimal.ddlog

2021-01-04 11:49 UTC, desharchana19 commented on tools/vscode/ddlog-language/src/good/meta.json5
> +                            "match": "(?<![:]\\s*)(?!.*(bigint|bit|bool|signed|double|float|string|Vec|Ref|Set|Map))\\s*([a-z_][a-zA-Z0-9_]*)(\\b)"
This pattern is a match for a argument of a function. The argument is of pattern ([a-z_][a-zA-Z0-9_]*). This pattern should exclude types. Hence, ?!.*(bigint|bit|bool|signed|double|float|string|Vec|Ref|Set|Map) is added.

2021-01-27 21:43 UTC, mbudiu-vmw commented
We will merge this as is and make subsequent improvements.
I will commit some simpler installation scripts in a future PR.

2021-01-27 21:44 UTC, mbudiu-vmw approved these changes

2021-01-27 21:52 UTC, merged