Work-in-Progress: C Tutorial
vmware/differential-datalog pull request #853
Opened 2020-12-10 18:03 UTC by smadaminov

This is an almost complete first part of the DDlog+C tutorial. Not much left to finish in the first part - mainly adding a couple of paragraph of discussion of the code and why the compilation command looks the way it looks. And then editing of course.

It's taking me quite long and there are bunch of things to finish in terms of writing. But I think creating a PR and getting an early feedback may be good.  And if there will be requested changes then I can also incorporate them earlier. Meanwhile, I will continue to gradually writing the rest of the tutorial and cleaning the code for it.

2020-12-10 22:46 UTC, mbudiu-vmw requested changes

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +	input relation Links(src: string, dst: string, link_status: bool)
I think you are using tabs. does .rst do something special to tabs? Otherwise I would suggest using spaces to get a predictable layout.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Let's briefly discuss the rule to calculate :code:`ConnectedNodes` relation. First, we say that any directly connected nodes such that the :code:`link_status` between them is :code:`true` belong to :
Is there a way to number lines and refer to them by number?

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +However, for the reachibility monitor to be useful it also should provide some output and not just ingest the data. We want our program to output a list of nodes that are currently reachable based on
your lines are long, so it's difficult to add git comments for a specific position.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Let's briefly discuss the rule to calculate :code:`ConnectedNodes` relation. First, we say that any directly connected nodes such that the :code:`link_status` between them is :code:`true` belong to :
Writing such a rule isn't any harder in other programming languages. What is much harder is computing it *incrementally*.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +	$ cd t1_reachibility_monitor_ddlog/ && cargo build --release
maybe you can say that the _ddlog directory is generated by the compiler

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +	$ ./target/release/t1_reachibility_monitor_cli
you can probably say that this starts a command-line program that lets you interact with the ddlog program currently running.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +If we check :code:`ConnectedNodes` we will see that this relation is empty, which make sense as we haven't populated relation :code:`Links` with anything yet:
check -> display the contents?

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Let's fix it. We are going to insert several records into :code:`Links` relation. But first let's define a simple network topology that we are going to work through. To make our life more interesting
you are not really fixing the program, you are supplying input data.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Something is off - some nodes are connected to themselves. But why this happened? If we take a closer look at our rule we can notice that this phenomenon actually make sense. For example, Santa Barba
before noticing that something is off you could say something about this containing the expected output.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +	output relation ConnectedNodes(str: string, dst: string)
do you want to use `src` here instead of `str`?

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +	ConnectedNodes{.src = "Los Angeles", .dst = "Los Angeles"}
this output is correct only if you used `.src` for `ConnectedNodes`

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +	$ cd t1_reachibility_monitor_ddlog/ && cargo build --release
Do you want to say something about the fact that this will take a while the first time, but be much faster later?

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +	output relation ConnectedNodes(str: string, dst: string)
src?

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Perfect! Now it looks exactly as what we expected! This is a good time to start doing what this tutorial promised and start writing some C code! We are going to start with something simple yet import
"as we expected?"

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Perfect! Now it looks exactly as what we expected! This is a good time to start doing what this tutorial promised and start writing some C code! We are going to start with something simple yet import
Before doing that do you want to show the incremental nature of DDlog by changing a link status in the CLI?

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +#include <stdio.h>
this file also has a mix of spaces and tabs

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Tutorial #1 - Reachibility Monitor
typo: reachability. This has to be fixed everywhere.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +#include "ddlog.h"
This is generated by the compiler in the _ddlog directory.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +* add the discussion of the code
is this supposed to be before the concludes?
You have to explain a lot of stuff about the code: ddog_record, the callback api, the notion of transaction (you could explain transactions even earlier in the cli section).

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +
you have to call ddlog_string_free(record_str);

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +    if (getline(&dst_line_ptr, &n, stdin) < 0) {
don't you have to reset n to 0?

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +    ddlog_cmd *cmds[1];
You probably don't need this one, you can just use &cmd.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +    ddlog_dump_table(prog, 0, &print_records_callback, 1);
why is the id 0 hardwired here?

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +    ddlog_dump_table(prog, 0, &print_records_callback, 1);
why is the last argument 1? it is a pointer...

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +    printf("Record: %s\n", record_str);
you probably want to show something about the weight too.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +#include "ddlog.h"
I would point at it explicitly, it has lots of comments and it really defines the API between DDlog and C.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +    ddlog_record* new_record = ddlog_struct("Links", struct_args, 3);
you may want to point out that the records do not have to be deleted: they will be consumed by the command.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +    ddlog_cmd* cmd = ddlog_insert_cmd(1, new_record);
you may also want to say that the command does not have to be deallocated.

2020-12-10 22:46 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/reachibility_monitor_p1.c
> +    ddlog_cmd* cmd = ddlog_insert_cmd(1, new_record);
why is the table id hardwired?

2021-01-29 16:54 UTC, ryzhyk commented
@smadaminov, is this PR ready for another review or are you still making changes to it?

2021-02-03 16:58 UTC, smadaminov commented
@ryzhyk there are few minor things left. Sorry, I thought I will update the PR and put it up for the review last week but got dragged by some family/work stuff. I hope I will sort it out this week.

2021-02-05 00:54 UTC, mbudiu-vmw requested changes
This is very good. I asked for a few small changes.

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +In this set of tutorials we are going to explore various features of DDlog programming language and learn how to integrate DDlog program into C program.
"a DDlog program into a C program"

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +In our first tutorial we are going to build a program that will calculate the reachability information in the network.
"in a network composed of nodes connected by links."
You are using nodes and links in the next phrase without having defined them.

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +We are going to test our program with the network consisting of four nodes: Menlo Park, Santa Barbara, Los Angeles, and Salt Lake City.
I would move these two lines a little lower, when you actually show how to insert the data.

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +In our program we need to supply source node, destination node, and a link status between them.
I would delete this line. Note that you are dealing with 2 programs: one is the DDlog program, and the other one is the .dat file with inputs. This text line seems more applicable to the latter really.

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Isn't is amazing?
Your users haven't seen yet how the incremental aspect works, so I don't know if they will appreciate it at this point.

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Note that DDlog is a `transaction-based`_ programming language.
You should probably be more precise here: there are really no transactions in the *.dl file, but when you supply inputs you do it using transactions; the outputs are also associated to transactions.

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +But why this happened?
why *has* this

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +Now we are finally realdy to start writing some C code!
why not make the text up to here the first tutorial and this one the second one?
You really have two tutorials: first is how to compile and run the CLI, second is how to integrate into a C program.
No additional work required.

2021-02-05 00:54 UTC, mbudiu-vmw commented on doc/tutorial/c_tutorial/c_tutorial.rst
> +It helps avoiding cluttering code if you want to apply multiple commands.
I would actually say that often applying multiple commands in a single transaction can be more efficient (batching).

2021-02-18 19:42 UTC, ryzhyk approved these changes

2021-02-18 19:44 UTC, ryzhyk commented
Before merging this, I will look into the memory leak issue reported by @smadaminov

2021-02-18 22:55 UTC, merged